import 'package:get/get.dart';

class LocalizationString extends Translations {

  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      // ☀️ Sun
      'sun_name': 'Sun',
      'sun_description': 'The star at the center of our solar system. It provides heat and light to all the planets and is essential for life on Earth.',
      'sun_fact_1': 'The Sun accounts for 99.86% of the mass in the Solar System.',
      'sun_fact_2': 'It’s a nearly perfect sphere of hot plasma.',
      'sun_fact_3': 'Energy from the Sun drives Earth’s climate and weather.',
      'sun_fact_4': 'The Sun is about 4.6 billion years old.',
      'sun_fact_5': 'Light from the Sun takes 8 minutes to reach Earth.',
      'sun_type': 'Star',
      'sun_atmosphere': 'Hydrogen and Helium',
      'sun_surface': 'Photosphere, Chromosphere, Corona',
      'sun_magnetic_field': 'Strong and complex',
      'sun_rings': 'None',

      // ☿ Mercury
      'mercury_name': 'Mercury',
      'mercury_description': 'The smallest and innermost planet in the Solar System. Despite its proximity to the Sun, Mercury is not the hottest planet, but it has the most extreme temperature variations.',
      'mercury_fact_1': 'Mercury is the fastest planet, orbiting the Sun every 88 Earth days.',
      'mercury_fact_2': 'The surface temperature varies from -180°C to 430°C.',
      'mercury_fact_3': 'Mercury has no moons and no substantial atmosphere.',
      'mercury_fact_4': 'It is the smallest planet in our solar system.',
      'mercury_fact_5': 'Despite being closest to the Sun, it is not the hottest planet.',
      'mercury_type': 'Terrestrial planet',
      'mercury_atmosphere': 'Minimal',
      'mercury_surface': 'Heavily cratered',
      'mercury_magnetic_field': 'Weak',
      'mercury_rings': 'None',

      // ♀ Venus
      'venus_name': 'Venus',
      'venus_description': 'The second planet from the Sun and similar in size to Earth. Venus is the hottest planet due to its thick, toxic atmosphere.',
      'venus_fact_1': 'Venus rotates in the opposite direction to most planets.',
      'venus_fact_2': 'Its day is longer than its year.',
      'venus_fact_3': 'Venus has a dense carbon dioxide atmosphere.',
      'venus_fact_4': 'It has surface temperatures around 465°C.',
      'venus_fact_5': 'It is sometimes called Earth’s twin.',
      'venus_type': 'Terrestrial planet',
      'venus_atmosphere': 'Carbon dioxide, Sulfuric acid',
      'venus_surface': 'Volcanic plains, highland regions',
      'venus_magnetic_field': 'None',
      'venus_rings': 'None',

      // 🌍 Earth
      'earth_name': 'Earth',
      'earth_description': 'Our home planet and the only known planet to support life. Earth has vast oceans, a breathable atmosphere, and diverse ecosystems.',
      'earth_fact_1': 'Earth is 70% covered by water.',
      'earth_fact_2': 'It is the only planet known to support life.',
      'earth_fact_3': 'Earth has one natural satellite — the Moon.',
      'earth_fact_4': 'It has an active magnetic field and plate tectonics.',
      'earth_fact_5': 'The Earth orbits the Sun every 365.25 days.',
      'earth_type': 'Terrestrial planet',
      'earth_atmosphere': 'Nitrogen and Oxygen',
      'earth_surface': 'Oceans, Continents, Mountains',
      'earth_magnetic_field': 'Strong and protective',
      'earth_rings': 'None',

      // ♂ Mars
      'mars_name': 'Mars',
      'mars_description': 'Often called the “Red Planet,” Mars has a thin atmosphere and surface features reminiscent of both the Moon and Earth.',
      'mars_fact_1': 'Mars has the tallest volcano in the solar system — Olympus Mons.',
      'mars_fact_2': 'It has two small moons: Phobos and Deimos.',
      'mars_fact_3': 'Evidence suggests Mars once had liquid water.',
      'mars_fact_4': 'Mars has seasons like Earth due to its tilt.',
      'mars_fact_5': 'Future missions aim to send humans to Mars.',
      'mars_type': 'Terrestrial planet',
      'mars_atmosphere': 'Carbon dioxide, Argon, Nitrogen',
      'mars_surface': 'Dusty, rocky with polar ice caps',
      'mars_magnetic_field': 'None',
      'mars_rings': 'None',

      // ♃ Jupiter
      'jupiter_name': 'Jupiter',
      'jupiter_description': 'The largest planet in the Solar System. Jupiter is a gas giant known for its Great Red Spot and powerful storms.',
      'jupiter_fact_1': 'Jupiter has at least 79 moons.',
      'jupiter_fact_2': 'Its Great Red Spot is a giant storm system.',
      'jupiter_fact_3': 'It has a very strong magnetic field.',
      'jupiter_fact_4': 'Jupiter emits more heat than it receives from the Sun.',
      'jupiter_fact_5': 'It takes about 12 Earth years to orbit the Sun.',
      'jupiter_type': 'Gas giant',
      'jupiter_atmosphere': 'Hydrogen and Helium',
      'jupiter_surface': 'No solid surface, gaseous',
      'jupiter_magnetic_field': 'Very strong',
      'jupiter_rings': 'Faint ring system',

      // ♄ Saturn
      'saturn_name': 'Saturn',
      'saturn_description': 'Known for its beautiful ring system, Saturn is a gas giant composed mostly of hydrogen and helium.',
      'saturn_fact_1': 'Saturn has over 80 moons.',
      'saturn_fact_2': 'Its rings are made of ice and rock.',
      'saturn_fact_3': 'Saturn is less dense than water.',
      'saturn_fact_4': 'It has a strong magnetic field.',
      'saturn_fact_5': 'One of its moons, Titan, has a thick atmosphere.',
      'saturn_type': 'Gas giant',
      'saturn_atmosphere': 'Hydrogen and Helium',
      'saturn_surface': 'No solid surface, gaseous',
      'saturn_magnetic_field': 'Strong',
      'saturn_rings': 'Prominent and complex',

      // ♅ Uranus
      'uranus_name': 'Uranus',
      'uranus_description': 'An ice giant with a unique tilt, Uranus rotates on its side and has a faint ring system.',
      'uranus_fact_1': 'Uranus has 27 known moons.',
      'uranus_fact_2': 'It rotates nearly horizontally.',
      'uranus_fact_3': 'Its blue color comes from methane in its atmosphere.',
      'uranus_fact_4': 'Discovered in 1781 by William Herschel.',
      'uranus_fact_5': 'It has a cold atmosphere and minimal heat emission.',
      'uranus_type': 'Ice giant',
      'uranus_atmosphere': 'Hydrogen, Helium, Methane',
      'uranus_surface': 'Gaseous with icy mantle',
      'uranus_magnetic_field': 'Tilted and off-center',
      'uranus_rings': '13 known faint rings',

      // ♆ Neptune
      'neptune_name': 'Neptune',
      'neptune_description': 'The farthest planet from the Sun, Neptune is an ice giant known for strong winds and a dark, cold atmosphere.',
      'neptune_fact_1': 'Neptune has the strongest winds in the solar system.',
      'neptune_fact_2': 'It has 14 known moons.',
      'neptune_fact_3': 'Its atmosphere is rich in methane.',
      'neptune_fact_4': 'It takes 165 Earth years to orbit the Sun.',
      'neptune_fact_5': 'It was discovered in 1846.',
      'neptune_type': 'Ice giant',
      'neptune_atmosphere': 'Hydrogen, Helium, Methane',
      'neptune_surface': 'Gaseous with icy core',
      'neptune_magnetic_field': 'Strong and tilted',
      'neptune_rings': '5 faint rings',

      // description typography
      'planet_name': 'Planet Name:',
      'planet_type': 'Planet Type:',
      'planet_atmosphere': 'Atmosphere:',
      'planet_surface': 'Surface:',
      'planet_magnetic_field': 'Magnetic Field:',
      'planet_rings': 'Rings:',
      'physical_characteristics': 'Physical Characteristics:',
      'interesting_facts': 'Interesting Facts:',
      'other_info': 'Other Information:',
      'diameter': 'Diameter:',
      'mass': 'Mass:',
      'orbital_period': 'Orbital Period:',
      'rotation_period': 'Rotation Period:',
      'distance_from_sun': 'Distance from Sun:',
    },
    'bn_BD': {
      // Mercury
      'mercury_name': 'বুধ',
      'mercury_description': 'সূর্য থেকে সবচেয়ে কাছে ও ছোট গ্রহ। সূর্যের কাছাকাছি থাকা সত্ত্বেও এটি সবচেয়ে গরম নয় বরং সবচেয়ে বেশি তাপমাত্রার পার্থক্য দেখা যায়।',
      'mercury_fact_1': 'বুধ সবচেয়ে দ্রুতগতির গ্রহ, এটি প্রতি ৮৮ দিনে সূর্যকে একবার প্রদক্ষিণ করে।',
      'mercury_fact_2': 'এর তাপমাত্রা -১৮০°C থেকে ৪৩০°C পর্যন্ত ওঠানামা করে।',
      'mercury_fact_3': 'বুধের কোনো উপগ্রহ নেই এবং এটি কোনও গুরুত্বপূর্ণ বায়ুমণ্ডল ধারণ করে না।',
      'mercury_fact_4': 'এটি সৌরজগতের সবচেয়ে ছোট গ্রহ।',
      'mercury_fact_5': 'সূর্যের সবচেয়ে কাছের গ্রহ হলেও এটি সবচেয়ে গরম নয়।',
      'mercury_type': 'স্থল গ্রহ',
      'mercury_atmosphere': 'নূন্যতম',
      'mercury_surface': 'গহ্বরপূর্ণ',
      'mercury_magnetic_field': 'দুর্বল',
      'mercury_rings': 'নেই',

      // Venus
      'venus_name': 'শুক্র',
      'venus_description': 'আকৃতি ও ভরের দিক থেকে পৃথিবীর সদৃশ হওয়ায় একে পৃথিবীর বোন বলা হয়। ঘন বায়ুমণ্ডল ও গ্রিনহাউস প্রভাবের কারণে এটি সবচেয়ে গরম গ্রহ।',
      'venus_fact_1': 'শুক্র অন্যান্য গ্রহের তুলনায় বিপরীত ঘূর্ণন করে।',
      'venus_fact_2': 'এর তাপমাত্রা প্রায় ৪৬২°C, যা সৌরজগতের সর্বোচ্চ।',
      'venus_fact_3': 'এর বায়ুমণ্ডল ৯৬% কার্বন ডাই অক্সাইড দ্বারা গঠিত, যার ফলে প্রচণ্ড গ্রিনহাউস প্রভাব সৃষ্টি হয়।',
      'venus_fact_4': 'শুক্রের কোনো উপগ্রহ বা বৃত্ত নেই।',
      'venus_fact_5': 'শুক্রের একটি দিন তার বছরের চেয়ে দীর্ঘ।',
      'venus_type': 'স্থল গ্রহ',
      'venus_atmosphere': 'ঘন, CO₂',
      'venus_surface': 'আগ্নেয়গিরির সমভূমি',
      'venus_magnetic_field': 'অত্যন্ত দুর্বল',
      'venus_rings': 'নেই',

      // Earth
      'earth_name': 'পৃথিবী',
      'earth_description': 'আমাদের বাসস্থান এবং একমাত্র পরিচিত গ্রহ যেখানে জীবন বিদ্যমান। এটি সূর্য থেকে তৃতীয় গ্রহ।',
      'earth_fact_1': 'এটি একমাত্র গ্রহ যার পৃষ্ঠে তরল পানি আছে।',
      'earth_fact_2': 'এটি একমাত্র গ্রহ যেখানে জীবন টিকে আছে।',
      'earth_fact_3': 'বায়ুমণ্ডলে ৭৮% নাইট্রোজেন ও ২১% অক্সিজেন রয়েছে।',
      'earth_fact_4': 'এটির একটি প্রাকৃতিক উপগ্রহ রয়েছে - চাঁদ।',
      'earth_fact_5': 'পৃথিবী সৌরজগতের সবচেয়ে ঘন গ্রহ।',
      'earth_type': 'স্থল গ্রহ',
      'earth_atmosphere': 'নাইট্রোজেন ও অক্সিজেন',
      'earth_surface': '৭০.৮% পানি, ২৯.২% ভূমি',
      'earth_magnetic_field': 'শক্তিশালী',
      'earth_rings': 'নেই',

      // Mars
      'mars_name': 'মঙ্গল',
      'mars_description': 'লাল গ্রহ নামে পরিচিত, মঙ্গল একটি শীতল মরুভূমির গ্রহ। এর পাতলা বায়ুমণ্ডল আছে এবং এতে অনেক পৃথিবীর মতো ভূ-গঠন দেখা যায়।',
      'mars_fact_1': 'এখানে সৌরজগতের সবচেয়ে বড় আগ্নেয়গিরি, অলিম্পাস মনস অবস্থিত।',
      'mars_fact_2': 'মঙ্গলের দুটি ছোট উপগ্রহ আছে: ফোবোস ও ডেইমোস।',
      'mars_fact_3': 'এর লাল বর্ণ এসেছে লৌহ অক্সাইড (জং) থেকে।',
      'mars_fact_4': 'এখানে সৌরজগতের বৃহত্তম ধূলিঝড় দেখা যায়।',
      'mars_fact_5': 'প্রমাণ পাওয়া গেছে যে একসময় এখানে তরল পানি প্রবাহিত হতো।',
      'mars_type': 'স্থল গ্রহ',
      'mars_atmosphere': 'পাতলা, CO₂',
      'mars_surface': 'পাথুরে, মরুভূমির মতো',
      'mars_magnetic_field': 'দুর্বল',
      'mars_rings': 'নেই',

      // Jupiter
      'jupiter_name': 'বৃহস্পতি',
      'jupiter_description': 'সৌরজগতের সবচেয়ে বড় গ্রহ বৃহস্পতি একটি গ্যাস দৈত্য। এর রয়েছে বৃহৎ লাল দাগ নামক একটি ঘূর্ণিঝড় এবং শক্তিশালী চৌম্বক ক্ষেত্র।',
      'jupiter_fact_1': 'বৃহস্পতির দিন সবচেয়ে ছোট।',
      'jupiter_fact_2': 'বৃহৎ লাল দাগ একটি ঝড়, যা ৪০০ বছরেরও বেশি সময় ধরে চলছে।',
      'jupiter_fact_3': 'এর ৭৯টিরও বেশি উপগ্রহ রয়েছে।',
      'jupiter_fact_4': 'এর চৌম্বক ক্ষেত্র সবচেয়ে শক্তিশালী।',
      'jupiter_fact_5': 'এটি অন্যান্য সব গ্রহের মোট ভরের চেয়েও বেশি ভারী।',
      'jupiter_type': 'গ্যাস দৈত্য',
      'jupiter_atmosphere': 'হাইড্রোজেন ও হিলিয়াম',
      'jupiter_surface': 'কোনো কঠিন পৃষ্ঠ নেই',
      'jupiter_magnetic_field': 'অত্যন্ত শক্তিশালী',
      'jupiter_rings': 'হালকা বৃত্ত',

      // Saturn
      'saturn_name': 'শনি',
      'saturn_description': 'এর অসাধারণ বৃত্তের জন্য বিখ্যাত শনি একটি গ্যাস দৈত্য এবং সৌরজগতের দ্বিতীয় বৃহত্তম গ্রহ।',
      'saturn_fact_1': 'শনির বৃত্তগুলো মূলত বরফ ও পাথরের তৈরি।',
      'saturn_fact_2': 'এর ৮২টিরও বেশি উপগ্রহ আছে, যার মধ্যে টাইটান বুধের চেয়েও বড়।',
      'saturn_fact_3': 'শনি পানিতে ভাসতে পারে যদি এত বড় বাথটাব থাকত।',
      'saturn_fact_4': 'এর গড় ঘনত্ব পানির চেয়েও কম।',
      'saturn_fact_5': 'এর বৃত্তগুলো গড়ে মাত্র ১০ মিটার পুরু।',
      'saturn_type': 'গ্যাস দৈত্য',
      'saturn_atmosphere': 'হাইড্রোজেন ও হিলিয়াম',
      'saturn_surface': 'কোনো কঠিন পৃষ্ঠ নেই',
      'saturn_magnetic_field': 'শক্তিশালী',
      'saturn_rings': 'প্রবল বৃত্ত',

      // Uranus
      'uranus_name': 'ইউরেনাস',
      'uranus_description': 'একটি বরফ দৈত্য গ্রহ যা একপাশে কাত হয়ে ঘোরে। এটি সবচেয়ে ঠান্ডা গ্রহ, যদিও এটি সবচেয়ে দূরের নয়।',
      'uranus_fact_1': 'ইউরেনাস পাশের দিকে ঘোরে, সম্ভবত একটি বড় সংঘর্ষের ফলে।',
      'uranus_fact_2': 'এর ২৭টি উপগ্রহ আছে যেগুলোর নাম সাহিত্য চরিত্র থেকে এসেছে।',
      'uranus_fact_3': 'এর বায়ুমণ্ডলে "হীরা বৃষ্টি" হতে পারে।',
      'uranus_fact_4': 'টেলিস্কোপ ব্যবহার করে আবিষ্কৃত প্রথম গ্রহ এটি।',
      'uranus_fact_5': 'এর সবুজ-নীল রং এসেছে মিথেন গ্যাস থেকে।',
      'uranus_type': 'বরফ দৈত্য',
      'uranus_atmosphere': 'হাইড্রোজেন, হিলিয়াম, মিথেন',
      'uranus_surface': 'কোনো কঠিন পৃষ্ঠ নেই',
      'uranus_magnetic_field': 'অনিয়মিত',
      'uranus_rings': 'পাতলা বৃত্ত',

      // Neptune
      'neptune_name': 'নেপচুন',
      'neptune_description': 'সৌরজগতের সবচেয়ে বেশি বাতাসপ্রবাহ বিশিষ্ট গ্রহ। এটি ঠান্ডা, অন্ধকার এবং সবচেয়ে দূরের গ্রহ।',
      'neptune_fact_1': 'নেপচুনে বাতাসের গতি ২১০০ কিমি/ঘণ্টা পর্যন্ত পৌঁছায়।',
      'neptune_fact_2': 'এর ১৪টি উপগ্রহ আছে, যার মধ্যে ট্রাইটন বিপরীত দিকে আবর্তিত হয়।',
      'neptune_fact_3': 'একটি নেপচুন বছর = ১৬৫ পৃথিবী বছর।',
      'neptune_fact_4': 'এটি গাণিতিক ভবিষ্যদ্বাণীর মাধ্যমে আবিষ্কৃত হয়েছিল।',
      'neptune_fact_5': 'দ্য গ্রেট ডার্ক স্পট একটি ঝড়, যা বৃহস্পতির গ্রেট রেড স্পটের মতো।',
      'neptune_type': 'বরফ দৈত্য',
      'neptune_atmosphere': 'হাইড্রোজেন, হিলিয়াম, মিথেন',
      'neptune_surface': 'কোনো কঠিন পৃষ্ঠ নেই',
      'neptune_magnetic_field': 'শক্তিশালী',
      'neptune_rings': 'হালকা বৃত্ত',

      // Sun
      'sun_name': 'সূর্য',
      'sun_description': 'সূর্য সৌরজগতের কেন্দ্রস্থলে অবস্থিত একটি গরম প্লাজমার প্রায় নিখুঁত গোলাকার তারা, যা পৃথিবীর জীবনের জন্য গুরুত্বপূর্ণ শক্তির উৎস।',
      'sun_fact_1': 'সূর্য সৌরজগতের মোট ভরের প্রায় ৯৯.৮৬% ধারণ করে।',
      'sun_fact_2': 'সূর্য মূলত হাইড্রোজেন (প্রায় ৭৫%) ও হিলিয়াম (প্রায় ২৪%) দিয়ে গঠিত।',
      'sun_fact_3': 'প্রতি সেকেন্ডে সূর্য প্রায় ৬০০ মিলিয়ন টন হাইড্রোজেন হিলিয়ামে রূপান্তর করে।',
      'sun_fact_4': 'সূর্যের পৃষ্ঠ তাপমাত্রা প্রায় ৫,৫০০ ডিগ্রি সেলসিয়াস।',
      'sun_fact_5': 'সূর্যের বয়স প্রায় ৪.৬ বিলিয়ন বছর এবং এটি এখনো মূল অনুক্রমে আছে।',
      'sun_type': 'তারা',
      'sun_atmosphere': 'করোনা, ক্রোমোস্ফিয়ার',
      'sun_surface': 'ফটোস্ফিয়ার',
      'sun_magnetic_field': 'সৌর চৌম্বক ক্ষেত্র',
      'sun_rings': 'নেই',

      // description typography

      'planet_name': 'গ্রহের নাম:',
      'planet_type': 'গ্রহের প্রকার:',
      'planet_atmosphere': 'বায়ুমণ্ডল:',
      'planet_surface': 'ভুপৃষ্ঠ:',
      'planet_magnetic_field': 'চৌম্বক ক্ষেত্র:',
      'planet_rings': 'বলয়:',
      'physical_characteristics': 'শারীরিক বৈশিষ্ট্য:',
      'interesting_facts': 'আকর্ষণীয় তথ্য:',
      'other_info': 'অন্যান্য তথ্য:',
      'diameter': 'ব্যাস:',
      'mass': 'ভর:',
      'orbital_period': 'কক্ষপথের সময়কাল:',
      'rotation_period': 'ঘূর্ণন সময়কাল:',
      'distance_from_sun': 'সূর্য থেকে দূরত্ব:',


    }
  };
}
